### ISSUE TITLE
Ensure that leaflet map can be hosted and displayed on a Wordpress site

### ISSUE THREAD

**Issue by mdlincoln** [dSHARP-CMU/bridgesofPittsburgh#111]
This has to happen ASAP so we know whether or not we'll need to come up with a non-wordpress site solution.

**Comment by mdlincoln** [comment]
Sample posted here: http://bridgesofpittsburgh.net/posts/106/

@ERSlayton can you document on here how this is working? What files are you uploading to the site, and how?

**Comment by ERSlayton** [comment]
After researching for a few hours, the process turned out to be very simple.

TO ADD R LEAFLET MAP TO WORDPRESS:

1) Save/export map as html file in R

2) Log in to WordPress.org Bridges site

3) Go to the Media Tab on the left hand side

4) Click 'Add New Media' button and add the html file

5) Click on the file you have just added, and select the 'edit more details' link on the right hand side

6) On the page that opens up, make sure to click the 'Update' button on the right hand side before copying the URL address 

7)  Then add a new page and use the following code in the 'TEXT' tab:

<iframe style="width: 100%; height: 120px;" 
src="urlnamehere">
</iframe>

**Comment by ERSlayton** [comment]
Update on what files I am working with: So far I have just added a test map. I will be deleting this example and then working on the route map that we really want to upload next.
